site :
  title: "Mario Souto - Timeline"
  description: "Bem vindo a minha timeline pessoal"
personal:
   name: "Mario Souto"
   avatar: "http://github.com/omariosouto.png"
   socialNetworks:
      youtube: "https://www.youtube.com/devsoutinho"
      github: "https://www.youtube.com/omariosouto"


